### ISSUE TITLE
Provide a way to send an event instead of logging

### ISSUE THREAD

**Issue by juh9870** [nicopap/bevy_mod_sysfail#4]
When a system in my game fails, I want to log an error and boot the player to a different state. I can do that by emitting an event, and handling it elsewhere.

Design of this crate looks amazing, I like the idea of having handling at call site rather than dozens of `pipe`s, but as it stands, there is no way to do anything more advanced than logging.

An option to emit an event would be a good start

**Comment by nicopap** [comment]
For historical context: The original idea was to extend this crate to work with systems as error handlers. Similarly to how currently in bevy you can do `systema.pipe(error)`, but through the macro instead of writing the `pipe` in the `add_systems` parameter.

### How would that work

I actually am not 100% sure it is possible. But I can imagine the following:

1. A new `trait`: `Sysfail: IntoSystem`. With a method either returning another system that can handle the output, or the method itself could work as a system.
2. A wrapper struct `SysfailSystem<S: Sysfail, E>(S, E)` Which itself would have a `IntoSystem` impl, so that it would be possible to create a system that pipes `S`'s output to `S`'s error handling system
3. Modify the `sysfail` macro to accept a new argument: `handler` which is an arbitrary system. With the `handler` argument, the system decorated with the `#[sysfail]` attribute would be renamed to `system_name_inner`, and would define a new top level item:

```rust
// This is a system
fn handle_error(In(err): In<Result<(), Err>>, mut event_writer: EventWriter<ChangeMenu>) {
  // ...
}

#[sysfail(handler = handle_error)]
fn my_system(q: Query<&Foo>) -> Result<(), Err> {
  // ...
}
```
Would then become:
```rust
fn handle_error(In(err): In<Err>, mut event_writer: EventWriter<ChangeMenu>) {
// ..

fn my_system_inner(q: Query<&Foo>) -> Result<(), Err> {
  // ...
}
#[allow(non_upper_case_globals)]
const my_system: Sysfail<
  fn(Query<&Foo>) -> Result<(), Err>,
  fn(In<Result<(), Err>>, EventWriter<ChangeMenu>),
> = Sysfail(my_system_inner, handle_error);
```

Again, not 100% sure it's possible. I'll probably have time to test it out in 10 days or so.

**Comment by nicopap** [comment]
It's not possible to do it the way I described it. Because `const` requires explicit full type declaration. So you would need to declare the type of the pipe receiver system. Really not ergonomic at all! But with a small tweak to `FailureMode` trait, it's possible to do absolute nonsense by expressing the wanted action in the type signature. Including emitting events

For example, here how you would emit events
```rust
#[sysfail]
fn emitting_failure(q: Query<…>, mut c: Commands, …) -> Result<(), Emit<MyEvent>> {
  let () = Err(MyEvent::Foo)?;
}
```

Then, in method `<Result<(), Emit<T>> as Failure>::get_error`, you could emit an event.

As long as `Emit<T>` implements `From<T>`, you can use `?` on errors of different types.

**Right now this is not possible** due to two things:
- the blanket impl on `impl<T: FailureMode> Failure for Result<(), T>`
- Not being able to access `EventWriter` in `get_error`.
 
So next version will have everything available for you to extend the `sysfail` macro through your own trait impls. This would also close #2 as `AppExit` is just an event.

## Change to logging

Now, we can imagine the fact of logging as just a different behavior, we could imagine a `Log<Err>` type that instead of emitting an event would create the log message. The problem is that we would lose the system's module path. Losing this is very bad, as it's quite useful in bevy to filter log messages.

## Declare return type in macro attribute

Finally, we could add syntax sugar for this by moving the `Err` of the result in the macro declaration:

```rust

```rust
#[sysfail]
fn emitting_failure(q: Query<…>, mut c: Commands, …) -> Result<(), Emit<MyEvent>> {
// becomes:
#[sysfail(Emit<MyEvent>)]
fn emitting_failure(q: Query<…>, mut c: Commands, …) {
```

This would avoid the boilerplate of `Result`, but it adds some abstraction I'm not too hot on.

**Comment by nicopap** [comment]
I've a prototype [at the `trait-failure` branch](https://github.com/nicopap/bevy_mod_sysfail/tree/trait-failure) if you care to try it, add the following section to your `Cargo.toml`:

```toml
[patch.crates-io]
bevy_mod_sysfail = { git = 'https://github.com/nicopap/bevy_mod_sysfail/', branch = "trait-failure" }
```
